# Site settings
title: A Paper Trail
description: Uncovering the reality of undocumented student access to higher education, across state borders
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://undocumented.dailybruin.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: :title/
editorsnote: > # shortened description for meta description tag
  <p>While federal legislation on undocumented immigrants continues to stall, 
  state policy continues to be a powerful predictor of the course of their lives. 
  Depending on where they've settled, undocumented students in the United States 
  can either be admitted to college with resident tuition and state aid, or they 
  can be banned from public institutions entirely.</p>
   
  <p>Reporter Natalie Delgadillo, opinion columnist Ryan Nelson and photojournalist 
  Angie Wang spent eleven months piecing together the full picture of what it 
  means to be an undocumented student in the United States, from California, where 
  policies are comparatively lenient, to Georgia, where students are subject to 
  some of the harshest higher education policies in the country.</p>

  <p>The Bridget O’Brien Scholarship Foundation has funded eight years of UCLA 
  student journalism with global reach and local impact, including this project. 
  To learn more about the scholarship, visit <a href="http://rememberingbridget.com">rememberingbridget.com</a>.</p>

# Build settings
markdown: kramdown
