# Site settings
title: A Paper Trail
description: Uncovering the reality of undocumented student access to higher education across state borders
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://undocumented.dailybruin.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: :title/
editorsnote: > # shortened description for meta description tag
  <p>The lives of undocumented people in the United States are at the whim of 
  state officials who create policy to fill the gaps in federal legislation.</p>

  <p>Some undocumented students in the United States are admitted to college with 
  resident tuition and state aid. Others - different only in where they live -  
  are banned from public institutions.</p>

  <p>Reporter Natalie Delgadillo, opinion columnist Ryan Nelson and photojournalist 
  Angie Wang spent 11 months piecing together what it means to be an undocumented 
  student in the United States. They looked at the lives of students in California, 
  where policies are comparatively lenient, and in Georgia, where students are subject 
  to some of the harshest higher education policies in the country. They found that 
  the stories of students in both states shed light on the arbitrary nature of 
  immigration policy in a country where federal action on the issue continues to stall.</p>

  <p>The Bridget O’Brien Scholarship Foundation has funded eight years of UCLA 
  student journalism with global reach and local impact, including this project. 
  To learn more about the scholarship, visit <a href="http://rememberingbridget.com">rememberingbridget.com</a>.</p>

# Build settings
markdown: kramdown
